### ISSUE TITLE
Concept and Roadmap for better news

### ISSUE THREAD

**Issue by mai-space** [mai-space-de/typo3-extension-better-news#1]
- [ ] Create default news record
- [ ] Create default news storage doktype
- [ ] News Controller list action
- [ ] News Controller show action
- [ ] News Widget recently created/published/archived
- [ ] Events for changing meta data, target page show action
- [ ] Concept for news routing (category based routing?)

**Comment by mai-space** [comment]
@mai-space-de/typo3-devs how should we route news? 

I guess something like tags would be logical but I think using typo3 categories for main topics would be the best usage for normal routing.

Also some from of Tag for more granular categorization of news would make sense but I think we should go ahead and maybe even copy or inherit the categories of typo3 and make a separate tree for tags...

Also, how do we want to route news on a page based manner.

I would like to route them like this:

Main-Domain.org/{possible-page}/{category}/{possible-sub-category}/{news-slug}

If a plugin for listing news is used on a different route the uri should still be the same as if you were on the page... Maybe we should pass the detail page into the news record itself and make it max 1.

This ensures correct routing even if you are on a different page or a different news.

Furthermore - what should we, by default, make part of the news record?

**Comment by Grigo91** [comment]
I will Start with the last Part, Whats should be a Part of the news record.

Based on the name, i would prefer to keep it simple . So a teaser text (optional), text, media, categories and maybe an author (maybe with an global option to use the creating backend User by default) should be enough.

Even some SEO related fields i wouldn't see there.

Maybe with an extra extension, to have a more or less, simple, extendable and more modular System, to realy just include WhatsApp you need.

So far, my two cents 😉

Oh and cause we are team orange, a kind of citation of an orange man, "make TYPO3 great(er) again!"

**Comment by mai-space** [comment]
I like the ideas! Let's start simple! But I would prefer a more straight forward approach to the tabs in a new record.

Something like: 
- Teaser: Title, Teaser, Thumbnail, detailpage
- Detail: Title, Bodytext, Media
- Relations: Categories, Authors, News
- (SEO as it's own extension)

What do you think? @Grigo91
